### ISSUE TITLE
Produce Dao layer, based on LocalDb database

### ISSUE THREAD

**Issue by EugeniZaplatin** [EugeniZaplatin/nrims#2]

**Comment by GavinVictor** [comment]
Разобрался в специфике подключения SQL Express LocalDb к проекту. Создал пустую базу NorisDb и положил её в проект RunTest. Настроил консоль на подключение к ней.
База копируется в выходной каталог, приложение подключается к ней, выполняет миграции структуры данных и далее может работать с этой базой, получать и вносить в неё изменения.
